=== cromerc/mt/ejemplos/mtbase.dtd
<?xml encoding="UTF-8"?>

		<!ELEMENT root (transicion)+>
		<!ATTLIST root xmlns CDATA #FIXED ''>

		<!ELEMENT transicion (movimiento|qi|qj|si|sj)+>
		<!ATTLIST transicion xmlns CDATA #FIXED ''>

		<!ELEMENT movimiento (#PCDATA)>
		<!ATTLIST movimiento xmlns CDATA #FIXED ''>

		<!ELEMENT qi (#PCDATA)>
		<!ATTLIST qi xmlns CDATA #FIXED ''>

		<!ELEMENT qj (#PCDATA)>
		<!ATTLIST qj xmlns CDATA #FIXED ''>

		<!ELEMENT si (#PCDATA)>
		<!ATTLIST si xmlns CDATA #FIXED ''>

		<!ELEMENT sj (#PCDATA)>
		<!ATTLIST sj xmlns CDATA #FIXED ''>

=== cromerc/mt/ejemplos/FirstLetterEqual(1).xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "mtbase.dtd">
<root>
	<transicion>
		<movimiento>R</movimiento>
		<si>a</si>
		<qj>1</qj>
		<qi>0</qi>
		<sj>#</sj>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>a</si>
		<sj>#</sj>
		<qj>1</qj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>b</si>
		<movimiento>R</movimiento>
		<qj>1</qj>
		<sj>#</sj>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>c</si>
		<qj>2</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>a</si>
		<qj>3</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>a</si>
		<qj>3</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>b</si>
		<qj>3</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>0</qi>
		<si>b</si>
		<qj>4</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>a</si>
		<qj>4</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>b</si>
		<qj>4</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>c</si>
		<qj>5</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>5</qi>
		<si>b</si>
		<qj>6</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>6</qi>
		<si>a</si>
		<qj>6</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>6</qi>
		<si>b</si>
		<qj>6</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
</root>

=== cromerc/mt/ejemplos/mT4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "mtbase.dtd">
<root>
	<transicion>
		<si>0</si>
		<qj>0</qj>
		<sj>0</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>0</qi>
		<si>1</si>
		<qj>1</qj>
		<movimiento>R</movimiento>
	</transicion>
</root>

=== cromerc/mt/ejemplos/FirstLetterEqual.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "mtbase.dtd">
<root>
	<transicion>
		<qi>0</qi>
		<si>a</si>
		<qj>1</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>a</si>
		<qj>1</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>b</si>
		<qj>1</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>c</si>
		<qj>2</qj>
		<sj>c</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>a</si>
		<qj>3</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>a</si>
		<qj>3</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>b</si>
		<qj>3</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>0</qi>
		<si>b</si>
		<qj>4</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>a</si>
		<qj>4</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>b</si>
		<qj>4</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>c</si>
		<qj>5</qj>
		<sj>c</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>5</qi>
		<si>b</si>
		<qj>6</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>6</qi>
		<si>a</si>
		<qj>6</qj>
		<sj>a</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>6</qi>
		<si>b</si>
		<qj>6</qj>
		<sj>b</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>#</si>
		<qj>7</qj>
		<sj>#</sj>
		<movimiento>S</movimiento>
	</transicion>
	<transicion>
		<qi>6</qi>
		<si>#</si>
		<qj>7</qj>
		<sj>#</sj>
		<movimiento>S</movimiento>
	</transicion>
</root>

=== cromerc/mt/ejemplos/Igual0sIgual1s.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "mtbase.dtd">
<root>
	<transicion>
		<qi>0</qi>
		<si>0</si>
		<qj>1</qj>
		<sj>X</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>0</si>
		<qj>1</qj>
		<sj>0</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>Y</si>
		<qj>1</qj>
		<sj>Y</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>1</qi>
		<si>1</si>
		<qj>2</qj>
		<sj>Y</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>X</si>
		<qj>0</qj>
		<sj>X</sj>
		<movimiento>R</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>0</si>
		<qj>2</qj>
		<sj>0</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>#</si>
		<qj>3</qj>
		<sj>#</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>1</si>
		<qj>2</qj>
		<sj>1</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>2</qi>
		<si>Y</si>
		<qj>2</qj>
		<sj>Y</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>Y</si>
		<qj>3</qj>
		<sj>Y</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>3</qi>
		<si>X</si>
		<qj>4</qj>
		<sj>X</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>X</si>
		<qj>4</qj>
		<sj>X</sj>
		<movimiento>L</movimiento>
	</transicion>
	<transicion>
		<qi>4</qi>
		<si>#</si>
		<qj>5</qj>
		<sj>#</sj>
		<movimiento>R</movimiento>
	</transicion>
</root>
